version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/web/Dockerfile
    image: haskala
    command: /start
    # bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - db
      - redis
      - solr
      - fuseki
      - mailserver

    environment:
      - DATABASE_URL=postgres://haskala:haskala@db:5432/haskala # postgres://USER:PASSWORD@HOST:PORT/NAME
      - REDIS_URL=redis://redis:6379/0
      - SOLR_URL=http://solr:8983/solr/haskala
      - FUSEKI_URL=http://fuseki:3030/haskala
      - EMAIL_HOST=mailserver
      - EMAIL_PORT=1025

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: haskala
      POSTGRES_USER: haskala
      POSTGRES_PASSWORD: haskala
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  solr:
    image: solr:8
    command:
      - solr-precreate
      - haskala
    ports:
      - "8983:8983"

  fuseki:
    image: stain/jena-fuseki
    environment:
      - ADMIN_PASSWORD=admin
    ports:
      - "3030:3030"
    command: /jena-fuseki/fuseki-server --mem --update --localhost /haskala

  mailserver:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  nginx:
    image: nginx:alpine
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  postgres_data:
