"""
Django settings for haskala project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import json
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import environ
from django.utils.translation import gettext_lazy as _

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)


# Environment variables
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

SECRET_KEY = env("SECRET_KEY", default="")
DEBUG = env.bool("DEBUG", default=False)

# ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

LANGUAGE_CODE = 'en-us'

# Application definition

INSTALLED_APPS = [
    "home",
    "search",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "django_extensions",
    "modelcluster",
    "taggit",
    # "wagtailfontawesome",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.postgres",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "debug_toolbar",
    "wagtail.api.v2",
    "leaflet",
    "wagtailmarkdown",
    "cookiebanner",
    "django.contrib.sitemaps",
    "rest_framework",
    "django_filters",
    "drf_spectacular",
    "djangordf",
]

MIDDLEWARE = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.cache.UpdateCacheMiddleware",
    "django.middleware.cache.FetchFromCacheMiddleware",
]

ROOT_URLCONF = "haskala.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(PROJECT_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "haskala.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "backup": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    },
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DATABASE_NAME", default=""),
        "USER": env("DATABASE_USER", default=""),
        "PASSWORD": env("DATABASE_PASSWORD", default=""),
        "HOST": env("DATABASE_HOST", default="localhost"),
        "PORT": env("DATABASE_PORT", default=""),
    },
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, "static"),
]

# ManifestStaticFilesStorage rewrites every collected asset to a
# content-hashed filename (e.g. haskala.4f2c8b.css) and serves a
# manifest that maps logical → hashed names. Combined with the long
# Cache-Control: immutable header in nginx, this lets browsers cache
# /static/* aggressively without ever serving a stale bundle after a
# deploy. The custom subclass turns off the default strict mode so a
# dangling url(...) reference in legacy CSS does not crash the
# `collectstatic` step of the docker build.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "haskala.storage.TolerantManifestStaticFilesStorage",
    },
}

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Wagtail settings

WAGTAIL_SITE_NAME = "Library of the Haskala"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "https://www.haskala-library.net"

WAGTAILADMIN_RICH_TEXT_EDITORS = {
    'default': {
        'WIDGET': 'wagtail.admin.rich_text.DraftailRichTextArea',
        'OPTIONS': {
            'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'link', 'document-link', 'image',
                         'embed', 'code', 'ol', 'ul', 'blockquote', 'hr'],
        }
    },
    'secondary': {
        'WIDGET': 'some.external.RichTextEditor',
    }
}

WAGTAILADMIN_EXTERNAL_LINK_CONVERSION = 'exact'

# WAGTAIL_DATE_FORMAT = '%d.%m.%Y.'
# WAGTAIL_DATETIME_FORMAT = '%d.%m.%Y. %H:%M'
# WAGTAIL_TIME_FORMAT = '%H:%M'

WAGTAIL_ALLOW_UNICODE_SLUGS = True

WAGTAIL_AUTO_UPDATE_PREVIEW = True

EMAIL_SUBJECT_PREFIX = '[Haskala Library] '

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env('REDIS_URL', default='redis://127.0.0.1:6379/haskala'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (0, 0),  # Coordinates for map center
    'DEFAULT_ZOOM': 13,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,
    'TILES': 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',  # OSM tiles
    'ATTRIBUTION_PREFIX': 'Powered by Django-Leaflet',
    'CDN': 'False',
}

CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'nonce-{{ nonce }}'")
CSP_STYLE_SRC = ("'self'", "'nonce-{{ nonce }}'")


WAGTAILMARKDOWN = {
    "autodownload_fontawesome": True,
    "allowed_tags": [],  # optional. a list of HTML tags. e.g. ['div', 'p', 'a']
    "allowed_styles": [],  # optional. a list of styles
    "allowed_attributes": {},  # optional. a dict with HTML tag as key and a list of attributes as value
    "allowed_settings_mode": "extend",  # optional. Possible values: "extend" or "override". Defaults to "extend".
    "extensions": [],  # optional. a list of python-markdown supported extensions
    "extension_configs": {},  # optional. a dictionary with the extension name as key, and its configuration as value
    "extensions_settings_mode": "extend",  # optional. Possible values: "extend" or "override". Defaults to "extend".
    # tab_length: tab width python-markdown uses when expanding tabs;
    # 4 is the python-markdown default.
    "tab_length": 4,
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Library of the Haskala API",
    "DESCRIPTION": "Read-only REST API for the Library of the Haskala database.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

COOKIEBANNER = {
    "title": _("Cookie settings"),
    "header_text": _("We are using cookies on this website. A few are essential, others are not."),
    "footer_text": _("Please accept our cookies"),
    "footer_links": [
        {"title": _("Legal Notice"), "href": "/legal-notice/"},
        {"title": _("Privacy Policy"), "href": "/privacy-policy/"},
        {"title": _("Cookie Policy"), "href": "/cookie-policy/"},
    ],
    "groups": [
        {
            "id": "essential",
            "name": _("Essential"),
            "description": _("Essential cookies allow this page to work."),
            "cookies": [
                {
                    "pattern": "cookiebanner",
                    "description": _("Meta cookie for the cookies that are set."),
                },
                {
                    "pattern": "csrftoken",
                    "description": _("This cookie prevents Cross-Site-Request-Forgery attacks."),
                },
                {
                    "pattern": "sessionid",
                    "description": _("This cookie is necessary to allow logging in, for example."),
                },
            ],
        },
        {
            "id": "analytics",
            "name": _("Analytics"),
            "optional": True,
            "cookies": [
                {
                    "pattern": "_pk_.*",
                    "description": _("Matomo cookie for website analysis."),
                },
            ],
        },
    ],
}


MATOMO_URL = env("MATOMO_URL", default="")
MATOMO_SITE_IDS = json.loads(os.environ.get("MATOMO_SITE_IDS", "{}"))
USE_X_FORWARDED_HOST = True

# RDF export (haskala_rdf). HASKALA_DUMPS_ROOT is the parent directory
# under which one subdirectory per dataset (named after HASKALA_SLUG)
# holds /current and /archive/<timestamp> snapshots.
HASKALA_DUMPS_ROOT = env("HASKALA_DUMPS_ROOT", default=os.path.join(BASE_DIR, "dumps"))
HASKALA_SLUG = env("HASKALA_SLUG", default="haskala")
HASKALA_GND_MAPPING_CSV = env("HASKALA_GND_MAPPING_CSV", default="")

# Auto-push to a remote SPARQL endpoint. Leave HASKALA_SPARQL_PUSH_URL
# empty to disable; the export step still writes its files to
# HASKALA_DUMPS_ROOT regardless.
#
# Default protocol is "gsp" (HTTP Graph Store Protocol — Fuseki accepts
# the wholesale graph replacement via PUT). The endpoint then is
# .../<dataset>/data, e.g.
#   HASKALA_SPARQL_PUSH_URL=http://fuseki:3030/haskala/data
# Set HASKALA_SPARQL_PUSH_PROTOCOL=update to use SPARQL 1.1 Update
# instead (endpoint .../<dataset>/update).
HASKALA_SPARQL_PUSH_URL = env("HASKALA_SPARQL_PUSH_URL", default="")
HASKALA_SPARQL_PUSH_GRAPH = env(
    "HASKALA_SPARQL_PUSH_GRAPH",
    default="http://data.judaicalink.org/data/haskala",
)
HASKALA_SPARQL_PUSH_PROTOCOL = env("HASKALA_SPARQL_PUSH_PROTOCOL", default="gsp")
HASKALA_SPARQL_PUSH_USER = env("HASKALA_SPARQL_PUSH_USER", default="")
HASKALA_SPARQL_PUSH_PASSWORD = env("HASKALA_SPARQL_PUSH_PASSWORD", default="")
HASKALA_SPARQL_PUSH_TIMEOUT = env("HASKALA_SPARQL_PUSH_TIMEOUT", default=60, cast=int)

# djangordf is the JudaicaLink-internal Django/RDF bridge. We use it
# from haskala_rdf.push() to talk SPARQL Update to Fuseki; the
# build_data_graph() pipeline keeps producing the raw rdflib graph
# (it encodes domain-specific ontology mappings djangordf doesn't
# know about) and the push then routes through djangordf's
# FusekiBackend so the same library handles writes everywhere in the
# JudaicaLink ecosystem.
#
# When HASKALA_SPARQL_PUSH_URL is empty djangordf falls back to its
# bundled InMemoryBackend (no network traffic) and the push() helper
# becomes a no-op — convenient for running the Django test suite or
# the management commands without a triple store at hand.
if HASKALA_SPARQL_PUSH_URL:
    # The FusekiBackend expects the dataset root, not the GSP/update
    # endpoint. Strip a trailing /data or /update so the user can paste
    # in either flavour as HASKALA_SPARQL_PUSH_URL.
    _dataset_root = HASKALA_SPARQL_PUSH_URL
    for _suffix in ("/data", "/update", "/query"):
        if _dataset_root.endswith(_suffix):
            _dataset_root = _dataset_root[: -len(_suffix)]
            break
    DJANGORDF_BACKEND = {
        "class": "djangordf.backends.fuseki.FusekiBackend",
        "endpoint": _dataset_root,
    }
    if HASKALA_SPARQL_PUSH_USER:
        DJANGORDF_BACKEND["user"] = HASKALA_SPARQL_PUSH_USER
        DJANGORDF_BACKEND["password"] = HASKALA_SPARQL_PUSH_PASSWORD
else:
    DJANGORDF_BACKEND = {
        "class": "djangordf.backends.memory.InMemoryBackend",
    }
DJANGORDF_DEFAULT_NAMESPACE = "http://data.judaicalink.org/data/haskala/"
DJANGORDF_DEFAULT_GRAPH = HASKALA_SPARQL_PUSH_GRAPH
DJANGORDF_NAMESPACES = {
    "hs": "http://data.judaicalink.org/ontology/haskala#",
    "hsk": "http://data.judaicalink.org/data/haskala/",
    "jl": "http://data.judaicalink.org/ontology/",
    "gndo": "http://d-nb.info/standards/elementset/gnd#",
}

# Mail
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="smtp.example.com")
EMAIL_PORT = env("EMAIL_PORT", default=465)
EMAIL_USE_TLS = env("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="")
SERVER_EMAIL = env("SERVER_EMAIL", default="")
