# Generated by Django 5.0.14 on 2025-12-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='legacy_tid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
