# Generated by Django 5.0.14 on 2025-12-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_language_legacy_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
