# Generated by Django 5.0.14 on 2025-12-08 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_language_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='digital_book_attributes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='digital_book_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='original_publication_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_publication_place_books', to='home.city'),
        ),
        migrations.AddField(
            model_name='book',
            name='width',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='width_format',
            field=models.CharField(blank=True, choices=[('', 'None'), ('NULL', 'Unknown'), ('text', 'Text'), ('filtered_html', 'Filtered HTML'), ('full_html', 'Full HTML'), ('markdown', 'Markdown'), ('xml', 'XML'), ('json', 'JSON')], default='NULL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='year_in_other_format',
            field=models.CharField(blank=True, choices=[('', 'None'), ('NULL', 'Unknown'), ('text', 'Text'), ('filtered_html', 'Filtered HTML'), ('full_html', 'Full HTML'), ('markdown', 'Markdown'), ('xml', 'XML'), ('json', 'JSON')], default='NULL', max_length=255, null=True),
        ),
    ]
