# Generated by Django 5.0.14 on 2025-12-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_book_digital_book_attributes_book_digital_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='not_available',
            field=models.BooleanField(default=False),
        ),
    ]
