# Generated by Django 5.0.14 on 2025-12-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_book_not_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='not_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
