# Generated by Django 5.0.14 on 2025-12-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_book_not_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='contradict_new_edition',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='contradict_original',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
