# Generated by Django 5.0.14 on 2025-12-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_book_availability_notes_format_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('pref_label',), 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
    ]
