# Generated by Django 5.0.14 on 2025-12-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_staticpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCustomModel',
        ),
        migrations.DeleteModel(
            name='MyCustomPage',
        ),
    ]
