# Generated by Django 5.0.14 on 2025-12-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_mycustommodel_delete_mycustompage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentationspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='imprintpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='privacypolicypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='termsandconditionspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='DocumentationsPage',
        ),
        migrations.DeleteModel(
            name='ImprintPage',
        ),
        migrations.DeleteModel(
            name='PrivacyPolicyPage',
        ),
        migrations.DeleteModel(
            name='TermsAndConditionsPage',
        ),
    ]
