# Generated by Django 5.0.14 on 2026-05-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_publisher_slug_series_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='name_in_book',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='production',
            name='person_name_appear',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='translation',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='edition',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
