# Generated by Django 5.0.14 on 2026-05-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_production_name_in_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preface',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
    ]
