# Generated by Django 5.0.14 on 2026-05-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_preface_notes_alter_translation_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preface',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
