# Generated by Django 5.0.14 on 2026-05-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_preface_title'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookauthor',
            constraint=models.UniqueConstraint(fields=('book', 'person', 'role'), name='unique_book_author_role'),
        ),
    ]
