# Generated by Django 5.0.14 on 2026-05-20 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_bookauthor_unique_book_author_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions', to='home.book'),
        ),
    ]
