# Generated by Django 6.0.5 on 2026-06-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_fix_accessibility_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gnd_id',
            field=models.CharField(blank=True, help_text='GND identifier (Gemeinsame Normdatei). Numeric ID only, e.g. 118582143 — gets prefixed with https://d-nb.info/gnd/ in the public link.', max_length=64),
        ),
    ]
