# Generated by Django 6.0.6 on 2026-06-11 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_reconnect_content_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='Canonical row this entry has been merged into. Setting this hides the row from listings but preserves the FK target for legacy data.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='home.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='parent_place',
            field=models.ForeignKey(blank=True, help_text='Containing/parent place if this is a district, village, or sub-region.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='home.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='wikidata_id',
            field=models.CharField(blank=True, default='', help_text="Wikidata QID, e.g. 'Q64' for Berlin.", max_length=32),
        ),
    ]
