# Generated by Django 6.0.6 on 2026-06-16 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0037_restore_brest_polen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('language', models.CharField(blank=True, default='', help_text="BCP-47 / ISO 639 language code (e.g. 'en', 'de', 'he', 'pl', 'uk', 'yi').", max_length=12)),
                ('value', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('wikidata', 'Wikidata'), ('manual', 'Manual'), ('import', 'Legacy import')], default='wikidata', max_length=32)),
                ('is_preferred', models.BooleanField(default=False, help_text='Mark the canonical label in this language. At most one preferred alias per (target, language) is enforced at the application layer.')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Alias name',
                'verbose_name_plural': 'Alias names',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='alias_target_idx'), models.Index(fields=['value'], name='alias_value_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'language', 'value'), name='unique_alias_per_target_lang_value')],
            },
        ),
    ]
