# Generated by Django 6.0.6 on 2026-06-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_person_wikidata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='entity_type',
            field=models.CharField(choices=[('person', 'Person (Wikidata Q5 / GND Tp)'), ('organization', 'Organization (Wikidata Q43229 / GND Tb)')], default='person', help_text="Switch to 'organization' for catalog rows that represent corporate bodies (schools, libraries, societies). Drives the Wikidata enrichment, the RDF class on output, and downstream filtering.", max_length=20),
        ),
    ]
