# Generated by Django 6.0.6 on 2026-06-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_classify_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='wikidata_id',
            field=models.CharField(blank=True, default='', help_text="Wikidata QID, e.g. 'Q937' for Albert Einstein.", max_length=32, null=True),
        ),
    ]
