# Generated by Django 6.0.6 on 2026-06-18 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_person_entity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='person',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='Canonical Person row this entry has been merged into. Setting this hides the row from listings but preserves the FK target for legacy data.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='home.person'),
        ),
    ]
